apiVersion: v1
kind: Pod
metadata:
  name: control-center
  namespace: rbac
  labels:
    app: control-center
spec:
  containers:
  - name: control-center
    image: gcr.io/solutionsarchitect-01/cp-enterprise-control-center-rbac
    ports:
      - containerPort: 9021
    # volumes:
    #   - ./conf:/tmp/conf
    env:
      # CUB CLASSPATH
      - name: CUB_CLASSPATH
        value: '/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-control-center/*:/usr/share/java/rest-utils/*:/usr/share/java/confluent-common/*'
      # CUB_CLASSPATH: '/etc/confluent/docker/docker-utils.jar:/usr/share/java/confluent-control-center/*'
      # general settings
      - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
        value: 'kafka:9092'
      - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
        value: 'zookeeper:2181'
      - name: CONTROL_CENTER_REPLICATION_FACTOR
        value: "1"
      - name: CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS
        value: "1"
      - name: CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS
        value: "1"
      - name: CONFLUENT_METRICS_TOPIC_REPLICATION
        value: "1"
      - name: PORT
        value: "9021"

      # ========================= other services ==============================
      # connect
      - name: CONTROL_CENTER_CONNECT_CONNECT1_CLUSTER
        value: http://connect:8083

      # ksql
      - name: CONTROL_CENTER_KSQL_KSQL1_URL
        value: http://ksql-server:8088
      - name: CONTROL_CENTER_KSQL_KSQL1_ADVERTISED_URL
        value: http://localhost:8088 # access KSQL from the browser

      # schema-registry
      - name: CONTROL_CENTER_SCHEMA_REGISTRY_URL
        value: http://schema-registry:8081

      # ========================= RBAC =================================
      - name: CONTROL_CENTER_REST_AUTHENTICATION_METHOD
        value: BEARER
      - name: PUBLIC_KEY_PATH
        value: /tmp/conf/public.pem

      - name: CONFLUENT_METADATA_BASIC_AUTH_USER_INFO
        value: hermes:hermes
      - name: CONFLUENT_METADATA_BOOTSTRAP_SERVER_URLS
        value: http://kafka:8090

      - name: CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL
        value: SASL_PLAINTEXT
      # The following configs are not required by C3 itself, but are required by cub to be able to connect to kafka to check if its ready
      # Seems like C3 would generate these configs when started, but cub runs before C3 starts, so it doesn't have access to these configs
      - name: CONTROL_CENTER_STREAMS_SASL_MECHANISM
        value: OAUTHBEARER
      - name: CONTROL_CENTER_STREAMS_SASL_LOGIN_CALLBACK_HANDLER_CLASS
        value: io.confluent.kafka.clients.plugins.auth.token.TokenUserLoginCallbackHandler
      - name: CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG
        value: |
               \
               org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
               username="hermes" \
               password="hermes" \
               metadataServerUrls="http://kafka:8090";
