apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: rbac
spec:
  containers:
  - name: zookeeper
    image: confluentinc/cp-zookeeper:5.4.0
    ports: 
    - containerPort: 2181
    env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: ZOOKEEPER_TICK_TIME
      value: "2000"
    
