---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
  name: zookeeper
spec:
  containers:
  - name: zookeeper
    image: "{{ .Values.zookeeper.image }}"
    ports:
    - containerPort: 2181
    env:
    - name: ZOOKEEPER_CLIENT_PORT
      value: "2181"
    - name: KAFKA_OPTS
      value: '-Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -DrequireClientAuthScheme=sasl'
