apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: default
spec:
  containers:
  - name: zookeeper
    image: gcr.io/${PROJECT}/zookeeper-sasl-scram
    resources:
      limits:
        memory: "1000Mi"
      requests:
        memory: "1000Mi"
    env: 
    - name: KAFKA_OPTS
      value: "-Djava.security.auth.login.config=/etc/kafka/zookeeper_server_jaas.conf"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181

---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  namespace: default
  labels:
    app: kafka
spec:
  containers:
  - name: kafka
    image: gcr.io/${PROJECT}/kafka-sasl-scram
    resources:
      limits:
        memory: "2000Mi"
      requests:
        memory: "2000Mi"
